### PR TITLE
Updated the complete readme file 

### PR DESCRIPTION
**Pull request by KGupta2601**
Added various sections in readme like the gssoc banner,statistics table for better visualization,stargazers and forkers

Fixes issues #48 

@sharmavikas4 kindly review my PR and provide the labels of gssoc extended and level 1

### CODE REVIEW

**Comment by sharmavikas4** [comment]
@KGupta2601  Not redirecting me to sections like Statistics, Pull Request Review Criteria, Code Of Conduct, Contributors, Stargazers, Forkers

**Comment by KGupta2601** [comment]
@sharmavikas4 Let me check and make the changes

**Comment by KGupta2601** [comment]
@sharmavikas4 I have made the changes...could you please check once
kindly review my PR and provide the labels of gssoc extended and level 1

**Comment by KGupta2601** [comment]
@sharmavikas4 could you please look into it
also provide the labels of gssoc extended and level 1

**Comment by KGupta2601** [comment]
@sharmavikas4 kindly review my PR and provide the labels of gssoc extended and level 1

**Comment by KGupta2601** [comment]
@MastanSayyad thank you sir

**Pull request merged**
