### PR TITLE
added chatbot for enhanced user experience 

### LINKED ISSUE #45: [Feat] Integrate a Chatbot for Instant User Support
### Description

Enhance the website's user experience by integrating a chatbot that provides instant answers to user inquiries. The chatbot should be easily accessible, provide relevant responses, and offer seamless assistance for common queries, improving user engagement and support.

Add a chatbot icon or button that floats on the bottom-right corner of the site.
When clicked, the chatbot window should expand with a smooth animation, displaying an input field and previous chat history.

The chatbot should respond to frequently asked questions (related to the FAQ section) and common inquiries about products or services.
Implement a fallback response for questions outside the chatbot's scope (e.g., "Sorry, I don't have an answer for that. Please contact our support team.").

please assign this to me under gssoc-ext and hacktoberfest

### Screenshots

https://github.com/user-attachments/assets/9617e9b6-e9fc-414c-9969-7f670d9985b5

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by sezallagwal**
## What does this PR do?

Fixes #45 
@sharmavikas4 please review this pr thanks!

https://github.com/user-attachments/assets/abea13a9-2390-4f54-9eed-657c26366b59

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by sharmavikas4** [comment]
@sezallagwal It is only showing the chatbot but it is not rendering anything else. A plain white background with chat bot only.
Screenshot 2024-10-28 122443

**Comment by sezallagwal** [comment]
image
Its working in my local environment, can you share logs

**Comment by sharmavikas4** [comment]
@sezallagwal but i am getting a white screen. Is there anything additional i have to do while setting up server and frontend

**Comment by sezallagwal** [comment]
@sharmavikas4 no nothing, check the auth setup it might be a backend issue and check logs what error you're getting

**Comment by sharmavikas4** [comment]
There is no error i am getting

**Comment by sharmavikas4** [comment]
@sezallagwal i am getting a white screen only

**Pull request closed without merging**
