### PR TITLE
Feature/implement category wise blogs

### LINKED ISSUE #37: [Feat] Implementing Category-wise Blogs
### Description

I will categorize blogs on the basis of whether it is a travel, health, tech, quotes, books, agricultural, industry, marketing or others type of blogs. For this, I will define category property in the post object of user schema and display the blogs on the basis of its category. If you want me to make these changes, please assign this issue to me with the particular labels.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by Sonalgupta2005**
## What does this PR do?

This PR will categorize the blogs on the basis of whether it is a travel, health, quotes, education, society, marketing, tech, fashion, art or others type of blogs. For this, I have defined category property in the post object of user schema and displayed the blogs on the basis of its category.

Fixes #37 
 
## Screenshot of the feature

image

If you liked this feature, please merge this into your website and assign me this PR with the particular labels.

### CODE REVIEW

**Comment by sharmavikas4** [comment]
Where is new section @Sonalgupta2005

**Comment by Sonalgupta2005** [comment]
@sharmavikas4 I have changed the name of new section to 'explore blogs' section as all the blogs including newly created are represented there.

**Comment by sharmavikas4** [comment]
You should add it to trending page also. Also, it should highlight which category it is showing and also when i deselect the categories it should show the blogs normally.

**Comment by Sonalgupta2005** [comment]
I have made the suggested changes. Please review it and suggest if any changes required.

**Comment by Sonalgupta2005** [comment]
@sharmavikas4 Any changes required?

**Comment by Sonalgupta2005** [comment]
@sharmavikas4 What is your opinion regarding this? Please suggest if any changes required.

**Comment by sharmavikas4** [comment]
@Sonalgupta2005 You haven't implemented the deselect option. When I select an option that is selected, it should deselect it instead of requiring me to select home to show blogs normally. Or the approach you have used, you should make sure the home is selected when the page render so that  user knows that it is showing all blogs.

**Comment by Sonalgupta2005** [comment]
@sharmavikas4  Now you can check the feature. It is as per your requirements. Please merge it with the particular labels.

**Comment by Sonalgupta2005** [comment]
@sharmavikas4  Please check the feature.

**Comment by sharmavikas4** [comment]
@Sonalgupta2005  Getting this error while editing post due to addition of category field . Fix this
```
Error editing blog: Error: USER validation failed: post.0.category: Path `category` is required.    
    at ValidationError.inspect (C:\Users\vikas\Downloads\MERN_BLOG\server\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at formatWithOptions (node:internal/util/inspect:2160:10)
    at console.value (node:internal/console/constructor:351:14)
    at console.warn (node:internal/console/constructor:384:61)
    at editBlog (file:///C:/Users/vikas/Downloads/MERN_BLOG/server/controller/blogController.js:252:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: {
    'post.0.category': ValidatorError: Path `category` is required.
        at validate (C:\Users\vikas\Downloads\MERN_BLOG\server\node_modules\mongoose\lib\schematype.js:1365:13)
        at SchemaType.doValidate (C:\Users\vikas\Downloads\MERN_BLOG\server\node_modules\mongoose\lib\schematype.js:1349:7)
        at C:\Users\vikas\Downloads\MERN_BLOG\server\node_modules\mongoose\lib\document.js:2968:18  
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'category',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true     
    }
  },
  _message: 'USER validation failed'
}
```

**Comment by Sonalgupta2005** [comment]
@sharmavikas4 I have fixed the edit bug. Now you can merge it.

**Comment by Sonalgupta2005** [comment]
@sharmavikas4 What's the update?

**Comment by sharmavikas4** [comment]
Lgtm @Sonalgupta2005 . Sorry for the inconvenience i was down due to medical issues. I am merging this you can now proceed with redesigning the website

**Pull request merged**
