### PR TITLE
Addition of All Contributors | Issue #15

### PR DESCRIPTION
**Pull request by Shariq2003**
Completed #15 

image

### CODE REVIEW

**Comment by sharmavikas4** [comment]
@Shariq2003  I want you to update readme and contributors.md so that the new contributors need to add their images in the readme to show their contribution.

**Comment by Shariq2003** [comment]
> @Shariq2003 I want you to update readme and contributors.md so that the new contributors need to add their images in the readme to show their contribution.

New Contributors will be added automatically based on the changes I made.

**Comment by Shariq2003** [comment]
@sharmavikas4 please merge this PR, it is in pending state since last 4 days

**Comment by sharmavikas4** [comment]
My bad @Shariq2003 . Great work .

**Comment by sharmavikas4** [comment]
Merged

**Pull request merged**
