### PR TITLE
Contributing.md File Created issue no #9 Resolved

### LINKED ISSUE #9: Add Contributing.md
I want to add contributing.md file to help the contributors that how to make issue and how to make a pull request.
@sharmavikas4 
Please assign this Issue to me..

### PR DESCRIPTION
**Pull request by rajatsinghal02**
#9 Resolved

Please Merge this Pull Request with the label attached.

### CODE REVIEW

**Comment by sharmavikas4** [comment]
remove bash from contributing.md 
eg
 ```
 ```bash
    cd server
    npm install
    cd ..
    cd client
    npm install
    ```
```
    It should be like this
```
    cd server
    npm install
    cd ..
    cd client
    npm install
    ```

**Comment by rajatsinghal02** [comment]
@sharmavikas4 I have updated the file please merge the pull request with following labels

**Comment by AKSHITHA-CHILUKA** [comment]
mention issue number in the description

**Comment by rajatsinghal02** [comment]
I have mentioned now

**Comment by AKSHITHA-CHILUKA** [comment]
Great @rajatsinghal02 follow it until the end of this program

**Comment by rajatsinghal02** [comment]
Yes sure

**Pull request merged**
