### PR TITLE
feat: added User Role System feature

### LINKED ISSUE #35: [Feat] User Role System
### Description

Implement a user role system that assigns different roles (admin, editor, user) with specific permissions for managing blog content.
This feature will allow for better content management, enabling specific users to edit or delete posts while restricting access for regular users.
Benefits:
Improved security through role-based access control.
Enhanced management of blog content and user interactions.
Better organization and functionality for blog administrators.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/sharmavikas4/MERN_BLOG/blob/main/contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by aashiimathur**
## What does this PR do?
Implement a user role system that assigns different roles (admin, editor, user) with specific permissions for managing blog content.
This feature will allow for better content management, enabling specific users to edit or delete posts while restricting access for regular users.

Fixes #35 

## Type of change

Implemented roles such as Admin, Editor, and User.
Added role definitions in the user model to ensure clarity and maintainability.
Implemented middleware to enforce role-based permissions on various endpoints.
Only Admin users can perform actions like creating, editing, or deleting blog posts.
Editors can edit existing posts but cannot delete them.
Regular Users can only view posts.
Updated the user interface to reflect role-specific actions.

### CODE REVIEW

**Comment by aashiimathur** [comment]
@sharmavikas4 one request - can you add 'hacktoberfest-accepted' label to my issue?

**Comment by sharmavikas4** [comment]
@aashiimathur resolve the conflict first

**Comment by aashiimathur** [comment]
> @aashiimathur resolve the conflict first
@sharmavikas4 
Resolved conflicting files.

**Comment by sharmavikas4** [comment]
@aashiimathur the application is broken . It is logging me in without asking me to sign in. Also there is no option to see trending,new and dashboard
Screenshot 2024-10-24 220959

**Comment by sharmavikas4** [comment]
Please begin from start and then implement and don't change the default configuration like port numbers etc

**Pull request closed without merging**
