### PR TITLE
Added website name and logo

### PR DESCRIPTION
**Pull request by Sonalgupta2005**
## What does this PR do?

I have added the name and logo of the website for a specific effect on the users.

image
---
Please suggest any changes if needed.
If you are merging this change, please assign me this PR with the particular labels.

### CODE REVIEW

**Comment by sharmavikas4** [comment]
Can we improve it @Sonalgupta2005 as it is not going with theme of the website

**Comment by Sonalgupta2005** [comment]
@sharmavikas4 Could I please modify the whole UI to a better version and match it with the theme of the website. If you want me to make these changes, I will make it in another issue and then you can assign me this issue with the particular labels.

**Comment by Sonalgupta2005** [comment]
@sharmavikas4 Please merge this PR into your website and then I can proceed with the modification of the UI of the website.

**Comment by Sonalgupta2005** [comment]
> @sharmavikas4 Please merge this PR into your website and then I can proceed with the modification of the UI of the website.

What is your opinion regarding this?

**Pull request merged**
